### ISSUE TITLE
Consulta - Mayordomo odia a alguien

### ISSUE THREAD

**Issue by Maxi-F** [ERSilvaPorras/PDP-TP-LOGICO#1]
Se podría realizar con una variable anónima, ya que no interesa saber quién es a quien odia el mayordomo.

https://github.com/ERSilvaPorras/PDP-TP-LOGICO/blob/ac33c62341bd7cdba64205c9f4cb9a40d8ca7956/muerte_en_la_mansion_Dreadbury/Muerte_en_la_mansi%C3%B3n_Dreadbury-2021.pl#L53

**Comment by ERSilvaPorras** [comment]
https://github.com/ERSilvaPorras/PDP-TP-LOGICO/blob/da2283f64cfb0168dd95b56ad8857f41754a130e/muerte_en_la_mansion_Dreadbury/Muerte_en_la_mansi%C3%B3n_Dreadbury-2021.pl#L64-L66
