### ISSUE TITLE
Tabulación de los predicados

### ISSUE THREAD

**Issue by Maxi-F** [ERSilvaPorras/PDP-TP-LOGICO#5]
Agregar la tabulación correspondiente para que quede mejor formateado el código.

Ejemplo:

```prolog
odiaA(charles, Odiado):- 
  viveEn(Odiado, mansion), 
  not(odiaA(tiaAgatha, Odiado)).
```

**Comment by ERSilvaPorras** [comment]
Gracias por remarcarme eso, tenia duda de usar TAB

**Comment by ERSilvaPorras** [comment]
https://github.com/ERSilvaPorras/PDP-TP-LOGICO/blob/da2283f64cfb0168dd95b56ad8857f41754a130e/muerte_en_la_mansion_Dreadbury/Muerte_en_la_mansi%C3%B3n_Dreadbury-2021.pl#L9-L29
