### ISSUE TITLE
Base de conocimiento - candidato/1 y partido/1

### ISSUE THREAD

**Issue by Maxi-F** [ERSilvaPorras/PDP-TP-LOGICO#6]
Ojo que `candidato` y `partido` no suman propiedades a los individuos que ya con las relaciones como por ejemplo `candidatura/2` y `sePostulaEn/2` ya brindan.

https://github.com/ERSilvaPorras/PDP-TP-LOGICO/blob/23dc9d23424df3d8685c1d7914079a55c197a042/Democracia/PDP-TP-LOGICO-DEMOCRACIA.pl#L7-L14

https://github.com/ERSilvaPorras/PDP-TP-LOGICO/blob/23dc9d23424df3d8685c1d7914079a55c197a042/Democracia/PDP-TP-LOGICO-DEMOCRACIA.pl#L27-L30

A modo de ejemplo, en esta parte del código utilizás `candidato` para generar al candidato, pero si hubieses utilizado `candidatura` directo podrías tomar el partido y no generar en la función auxiliar.

https://github.com/ERSilvaPorras/PDP-TP-LOGICO/blob/23dc9d23424df3d8685c1d7914079a55c197a042/Democracia/PDP-TP-LOGICO-DEMOCRACIA.pl#L193-L196

https://github.com/ERSilvaPorras/PDP-TP-LOGICO/blob/23dc9d23424df3d8685c1d7914079a55c197a042/Democracia/PDP-TP-LOGICO-DEMOCRACIA.pl#L199-L201

**Comment by ERSilvaPorras** [comment]
Buenas tardes, decidi quitar los hechos `candidato` y `partido`  ya que como bien menciono no suman propiedades a los individuos que ya quedan satisfechos con  las relaciones `candidatura/2` y `sePostulaEn/2`.
